# Generated by Django 6.0 on 2026-01-06 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('requirements_engine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonafide_type', models.CharField(choices=[('DEPARTMENT', 'Department'), ('COLLEGE', 'College')], max_length=20)),
                ('current_state', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('AI_VALIDATION_FAILED', 'Ai Validation Failed'), ('AWAITING_TUTOR_REVIEW', 'Awaiting Tutor Review'), ('AWAITING_STUDENT_UPDATE', 'Awaiting Student Update'), ('AWAITING_PC_APPROVAL', 'Awaiting Pc Approval'), ('AWAITING_HOD_APPROVAL', 'Awaiting Hod Approval'), ('AWAITING_DEAN_APPROVAL', 'Awaiting Dean Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('final_decision_at', models.DateTimeField(blank=True, null=True)),
                ('current_requirement_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='requirements_engine.requirementversion')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMMENTED', 'Commented')], max_length=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('state_at_action', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='approval_requests.approvalrequest')),
            ],
        ),
    ]
